config/routes.rb
Rails.application.routes.draw do  
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	root 'templates#index'
	resources :templates	
  	resources :sports do
		resources :sportswises	
	end
	resources :sportskits do
			get :buy
	end
	resources :currencies
	resources :addtoservices
	resources :sportsdictionary
	resources :contact do 
		get :sendmail
	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sport.rb
class Sport < ApplicationRecord
	has_many :sportkits
end

app/controllers/sports_controller.rb
require 'net/http'
require 'json'
require 'openssl'
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]

  # GET /sports
  # GET /sports.json
  def index
    begin
    @country=""
    @sportsplayed=""
    @countrywisesports=""
    @sortedsports
    url = 'https://sportsrest.azurewebsites.net/api/sports/listall'
    uri = URI(url)
    response = Net::HTTP.get(uri)
    result = JSON.parse(response)
    result.each do |res|
      @country = res["country"]
      @sportsplayed = res["sportsplayed"]
      @countrywisesports = @countrywisesports + @country.to_s + "-" + @sportsplayed.to_s + ";"
    end
    @sportsadded = Sport.all
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
  end

  # GET /sports/new
  def new
    begin
    @sport = Sport.new
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # GET /sports/1/edit
  def edit
  end

  # POST /sports
  # POST /sports.json
  def create    
    begin 
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    begin
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    begin
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Sport was successfully destroyed.' }
      format.json { head :no_content }
    end
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sport_params
      params.require(:sport).permit(:sport)
    end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_with(model: sport, local: true) do |form| %>
  <% if sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
        <% sport.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div>  
  <%= form.label :sport %>
  <%= form.text_area :sport %>
</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing Sport</h1>

<%= render 'form', sport: @sport %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countrywise Sports</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>   
    <% @checkingsize = @countrywisesports.split(";").size() %>
    <% if @checkingsize > 1 %>
    <% @countrywisesports = @countrywisesports.split(";") %>
    <% @countrywisesports.each do |sport| %>
    <% @sports = sport.split("-") %>
      <tr>
        <td><%= @sports[0] %></td>
         <td> : </td>
        <td>Sports played in <%= @sports[0] %> are <%= @sports[1] %></td>
      </tr>
    <% end %>
    <% else %>
      <% @sports = @countrywisesports.split("-") %>
      <tr>
        <td><%= @sports[0] %></td>
        <td> : </td>
        <td>Sports played in <%= @sports[0] %> are <%= @sports[1] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% unless current_user && current_user.admin? %>
<% else %>
<%= link_to 'New Sport', new_sport_path %>
<h4>Below are the sports added so far :</h4>
<% if @sports != nil %>
  <% if @sportsadded.size() > 1 %>
    <% @sportsadded.each do |sport| %>
    <%= sport.sport %></br>
  <% end %>
<% end %>
<% end %>
<% end %>

app/views/sports/new.html.erb
<h1>New Sport</h1>

<%= render 'form', sport: @sport %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>