config/routes.rb
Rails.application.routes.draw do  
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	root 'templates#index'
	resources :templates	
  	resources :sports do
		resources :sportswises	
	end
	resources :sportskits do
			get :buy
	end
	resources :currencies
	resources :addtoservices
	resources :sportsdictionary
	resources :contact do 
		get :sendmail
	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/sportswises_controller.rb
class SportswisesController < ApplicationController
  before_action :set_sportswise, only: [:show, :edit, :update, :destroy]

  # GET /sportswises
  # GET /sportswises.json
  def index
    begin
    @sport = Sport.find(params[:sport_id])
    @sportskits = Sportskit.all.where(:sport_id => @sport.id)
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # GET /sportswises/1
  # GET /sportswises/1.json
  def show
  end

  # GET /sportswises/new
  def new
    begin
    @sportswise = Sportswise.new
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # GET /sportswises/1/edit
  def edit
  end

  # POST /sportswises
  # POST /sportswises.json
  def create
    begin
    @sportswise = Sportswise.new(sportswise_params)

    respond_to do |format|
      if @sportswise.save
        format.html { redirect_to @sportswise, notice: 'Sportswise was successfully created.' }
        format.json { render :show, status: :created, location: @sportswise }
      else
        format.html { render :new }
        format.json { render json: @sportswise.errors, status: :unprocessable_entity }
      end
    end
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # PATCH/PUT /sportswises/1
  # PATCH/PUT /sportswises/1.json
  def update
    begin
    respond_to do |format|
      if @sportswise.update(sportswise_params)
        format.html { redirect_to @sportswise, notice: 'Sportswise was successfully updated.' }
        format.json { render :show, status: :ok, location: @sportswise }
      else
        format.html { render :edit }
        format.json { render json: @sportswise.errors, status: :unprocessable_entity }
      end
    end
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # DELETE /sportswises/1
  # DELETE /sportswises/1.json
  def destroy
    begin
    @sportswise.destroy
    respond_to do |format|
      format.html { redirect_to sportswises_url, notice: 'Sportswise was successfully destroyed.' }
      format.json { head :no_content }
    end
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sportswise
      @sportswise = Sportswise.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sportswise_params
      params.require(:sportswise).permit(:sportskit, :sports_id)
    end
end

app/helpers/sportswises_helper.rb
module SportswisesHelper
end

app/views/sportswises/_form.html.erb
<%= form_with(model: sportswise, local: true) do |form| %>
  <% if sportswise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sportswise.errors.count, "error") %> prohibited this sportswise from being saved:</h2>

      <ul>
        <% sportswise.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sportskit %>
    <%= form.text_field :sportskit %>
  </div>

  <div class="field">
    <%= form.label :sports_id %>
    <%= form.text_field :sports_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sportswises/edit.html.erb
<h1>Editing Sportswise</h1>

<%= render 'form', sportswise: @sportswise %>

<%= link_to 'Show', @sportswise %> |
<%= link_to 'Back', sportswises_path %>

app/views/sportswises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kits available for <%= Sport.find(params[:sport_id]).sport %></h1>

<table>
  <thead>
    <tr>
      <th>Sportskit</th>
      <th>Currency</th>
      <th>Price</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @sportskits.each do |sportskit| %>
      <tr>
        <td><%= sportskit.kit %></td>
        <td><%= sportskit.currency %></td>
        <td><%= sportskit.price %></td>
        <% unless current_user && current_user.admin? %>
        <td><%= link_to 'Buy', sportskit_buy_path(sportskit) %></td>
        <% else %>
        <td><%= link_to 'Show', sportskit %></td>
        <td><%= link_to 'Edit', edit_sportskit_path(sportskit) %></td>
        <td><%= link_to 'Destroy', sportskit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/sportswises/new.html.erb
<h1>New Sportswise</h1>

<%= render 'form', sportswise: @sportswise %>

<%= link_to 'Back', sportswises_path %>

app/views/sportswises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sportskit:</strong>
  <%= @sportswise.sportskit %>
</p>

<p>
  <strong>Sports:</strong>
  <%= @sportswise.sports_id %>
</p>

<%= link_to 'Edit', edit_sportswise_path(@sportswise) %> |
<%= link_to 'Back', sportswises_path %>