config/routes.rb
Rails.application.routes.draw do  
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	root 'templates#index'
	resources :templates	
  	resources :sports do
		resources :sportswises	
	end
	resources :sportskits do
			get :buy
	end
	resources :currencies
	resources :addtoservices
	resources :sportsdictionary
	resources :contact do 
		get :sendmail
	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sportskit.rb
class Sportskit < ApplicationRecord
	belongs_to :sports, optional: true
end

app/controllers/sportskits_controller.rb
class SportskitsController < ApplicationController
  before_action :set_sportskit, only: [:show, :edit, :update, :destroy]

  # GET /sportskits
  # GET /sportskits.json
  def index
    begin
    @sportskits = Sportskit.all
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # GET /sportskits/1
  # GET /sportskits/1.json
  def show
  end

  # GET /sportskits/new
  def new
    begin
  unless current_user && current_user.admin?
    render :text => "Access Error Message", :status => :unauthorizedend
  else  
    @sportskit = Sportskit.new
  end
  rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # GET /sportskits/1/edit
  def edit
  end

  def buy
    begin
    @sportskit = Sportskit.find(params[:sportskit_id])
    @sportskit_id=params[:sportskit_id]
    @invoicenum = Invoice.maximum("invoicenumber")
    if @invoicenum == nil
      @invoicenum=1
      @invoice=Invoice.new(:invoicenumber => @invoicenum, :product_id => @sportskit_id)
      @invoice.save
    else
      @invoicenum=@invoicenum+1      
      @invoice=Invoice.new(:invoicenumber => @invoicenum, :product_id => @sportskit_id)
      @invoice.save
    end
    @url = "https://hotelapi20200806072002.azurewebsites.net/invoice/getitems?invoiceNumber="+@invoicenum.to_s+"&customerName="+current_user.email.to_s+"&productName="+@sportskit.kit.to_s+"&productName=&productPrice="+@sportskit.currency.to_s+" "+@sportskit.price.to_s+"&productPrice=&totalAmt="+@sportskit.price.to_s+"&balanceAmt=5&transactionType=Credit/Debit_Card&siteName=SportsClientApp"
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end  

  # POST /sportskits
  # POST /sportskits.json
  def create
    begin
    @sportskit = Sportskit.new(sportskit_params)
    respond_to do |format|
      if @sportskit.save
        format.html { redirect_to @sportskit, notice: 'Sportskit was successfully created.' }
        format.json { render :show, status: :created, location: @sportskit }
      else
        format.html { render :new }
        format.json { render json: @sportskit.errors, status: :unprocessable_entity }
      end
    end
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # PATCH/PUT /sportskits/1
  # PATCH/PUT /sportskits/1.json
  def update
    begin
    respond_to do |format|
      if @sportskit.update(sportskit_params)
        format.html { redirect_to @sportskit, notice: 'Sportskit was successfully updated.' }
        format.json { render :show, status: :ok, location: @sportskit }
      else
        format.html { render :edit }
        format.json { render json: @sportskit.errors, status: :unprocessable_entity }
      end
    end
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # DELETE /sportskits/1
  # DELETE /sportskits/1.json
  def destroy
    begin
    @sportskit.destroy
    respond_to do |format|
      format.html { redirect_to sportskits_url, notice: 'Sportskit was successfully destroyed.' }
      format.json { head :no_content }
    end
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sportskit
      @sportskit = Sportskit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sportskit_params
      params.require(:sportskit).permit(:sport_id, :kit, :currency, :price)
    end
end

app/helpers/sportskits_helper.rb
module SportskitsHelper
end

app/views/sportskits/_form.html.erb
<%= form_with(model: sportskit, local: true) do |form| %>
  <% if sportskit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sportskit.errors.count, "error") %> prohibited this sportskit from being saved:</h2>

      <ul>
        <% sportskit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>     
    <%= form.label :sport %>
    <% sport_array=Sport.all.map {|sport| [sport.sport,sport.id]} %>
    <%= form.select :sport_id, options_for_select(sport_array) %>
  </div>
  <div>  
    <%= form.label :kit %>
    <%= form.text_area :kit %>
  </div>
  <div>     
    <%= form.label :currency %>
    <% currency_array=Currency.all.map {|curr| [curr.currencytype]} %>
    <%= form.select :currency, options_for_select(currency_array) %>
  </div>
  <div>     
    <%= form.label :price %>
    <%= form.text_area :price %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sportskits/buy.html.erb
<h4>Buyer's Page</h4>
<h2>Congrats!!! You purchased the below item</h2>
<table>
  <thead>
    <tr>
      <th>Sportskit</th>
      <th>Currency</th>
      <th>Price</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @sportskit.kit %></td>
        <td><%= @sportskit.currency %></td>
        <td><%= @sportskit.price %></td>
        <td><%= link_to 'Generate Invoice', @url %></td>
      </tr>
  </tbody>
</table>

app/views/sportskits/edit.html.erb
<h1>Editing Sportskit</h1>

<%= render 'form', sportskit: @sportskit %>

<%= link_to 'Show', @sportskit %> |
<%= link_to 'Back', sportskits_path %>

app/views/sportskits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sports Kits</h1>
<h3>Please select your sport</h3>

<div class="wrapper">
  <div style="display: block;"> 
    <div class="box cricket" style="position: relative;" >
    </div>
    <center><%= link_to 'Cricket', sport_sportswises_path('1') %></center>  
  </div>
  <div style="display: block;"> 
  <div class="box football" style="position: relative;"></div>
<center><%= link_to 'Football', sport_sportswises_path('2') %></center>
  </div>
  <div style="display: block;"> 
  <div class="box hockey" style="position: relative;"></div>
  <center><%= link_to 'Hockey', sport_sportswises_path('3') %></center></div>
  <div style="display: block;"> 
  <div class="box badminton" style="position: relative;"></div>
  <center><%= link_to 'Badminton', sport_sportswises_path('4') %></center></div>
<div style="display: block;"> 
  <div class="box tabletennis" style="position: relative;"></div>
  <center><%= link_to 'Table Tennis', sport_sportswises_path('6') %></center></div>
  <div style="display: block;"> 
  <div class="box tennis" style="position: relative;"></div>
  <center><%= link_to 'Tennis', sport_sportswises_path('5') %></center></div>
  <div style="display: block;"> 
  <div class="box handball" style="position: relative;"></div>
  <center><%= link_to 'Hand Ball', sport_sportswises_path('8') %></center></div>
  <div style="display: block;"> 
  <div class="box volleyball" style="position: relative;"></div>
  <center><%= link_to 'Volley Ball', sport_sportswises_path('2') %></center></div>
  <div style="display: block;"> 
  <div class="box swimming" style="position: relative;"></div><center><%= link_to 'Swimming', sport_sportswises_path('2') %></center></div>
  <div style="display: block;"> 
  <div class="box hurling" style="position: relative;"></div><center><%= link_to 'Hurling', sport_sportswises_path('2') %></center></div>
  <div style="display: block;"> 
  <div class="box baseball" style="position: relative;"></div><center><%= link_to 'Baseball', sport_sportswises_path('2') %></center></div>
  <div style="display: block;"> 
  <div class="box rugby" style="position: relative;"></div><center><%= link_to 'Rugby', sport_sportswises_path('2') %></center></div>
</div>

<div>
<br>
<% unless current_user && current_user.admin? %>  
  <% else %>
  <table>
  <thead>
    <tr>
      <th>Sport</th>
       <th>Kit</th>
       <th>Currency</th>
       <th>Price</th>
       <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @sportskits.each do |sportskit| %>
      <tr>
        <td><%= Sport.find(sportskit.sport_id).sport %></td>
        <td><%= sportskit.kit %></td>
        <td><%= sportskit.currency %></td>
        <td><%= sportskit.price %></td>
        <td><%= link_to 'Show', sportskit %></td>
        <td><%= link_to 'Edit', edit_sportskit_path(sportskit) %></td>
        <td><%= link_to 'Destroy', sportskit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Sportskit', new_sportskit_path %>
<% end %>
</div>

app/views/sportskits/new.html.erb
<h1>New Sportskit</h1>

<%= render 'form', sportskit: @sportskit %>

<%= link_to 'Back', sportskits_path %>

app/views/sportskits/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sportskit_path(@sportskit) %> |
<%= link_to 'Back', sportskits_path %>