config/routes.rb
Rails.application.routes.draw do  
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	root 'templates#index'
	resources :templates	
  	resources :sports do
		resources :sportswises	
	end
	resources :sportskits do
			get :buy
	end
	resources :currencies
	resources :addtoservices
	resources :sportsdictionary
	resources :contact do 
		get :sendmail
	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/addtoservice.rb
class Addtoservice < ApplicationRecord
	validates :country, :sportsplayed, :presence => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
	validates :currencytype, :presence => true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/sport.rb
class Sport < ApplicationRecord
	has_many :sportkits
end

app/models/sportskit.rb
class Sportskit < ApplicationRecord
	belongs_to :sports, optional: true
end

app/models/sportswise.rb
class Sportswise < ApplicationRecord
  belongs_to :sports
end

app/models/template.rb
class Template < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]


   def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
  end
end      
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def sendmail
  end
end

app/controllers/sports_controller.rb
require 'net/http'
require 'json'
require 'openssl'
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]

  # GET /sports
  # GET /sports.json
  def index
    begin
    @country=""
    @sportsplayed=""
    @countrywisesports=""
    @sortedsports
    url = 'https://sportsrest.azurewebsites.net/api/sports/listall'
    uri = URI(url)
    response = Net::HTTP.get(uri)
    result = JSON.parse(response)
    result.each do |res|
      @country = res["country"]
      @sportsplayed = res["sportsplayed"]
      @countrywisesports = @countrywisesports + @country.to_s + "-" + @sportsplayed.to_s + ";"
    end
    @sportsadded = Sport.all
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
  end

  # GET /sports/new
  def new
    begin
    @sport = Sport.new
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # GET /sports/1/edit
  def edit
  end

  # POST /sports
  # POST /sports.json
  def create    
    begin 
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    begin
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    begin
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Sport was successfully destroyed.' }
      format.json { head :no_content }
    end
    rescue Exception => e
    puts ("Found Exception : "+e.to_s)
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sport_params
      params.require(:sport).permit(:sport)
    end
end

app/helpers/addtoservice_helper.rb
module AddtoserviceHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/currency_helper.rb
module CurrencyHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/sportsdictionary_helper.rb
module SportsdictionaryHelper
end

app/helpers/sportskits_helper.rb
module SportskitsHelper
end

app/helpers/sportswises_helper.rb
module SportswisesHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sportsclientapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless current_user %>   
    <% else %> 
    <div class="navbar">
      <a href=<%= root_path %>>Home</a>
      <a href=<%= sports_path %>>Countrywise Sports</a>
      <a href=<%= sportsdictionary_index_path %>>Sports Dictionary</a>
      <a href=<%= sportskits_path %>>Sports Kit</a>
      <a href=<%= contact_index_path %>>Contact</a>
      <% unless current_user && current_user.admin? %>
    <% else %>
      <a href=<%= new_addtoservice_path %>>Post to Restful Webservice</a>
      <% end %>
      <a> 
    <%= link_to "Logout", destroy_user_session_path, method: :delete %></a>
    </div>    
    <% end %>

  </br>
</br>
    <%= yield %>
  </body>
</html>

app/views/templates/_form.html.erb
<%= form_with(model: template, local: true) do |form| %>
  <% if template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
        <% template.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<p id="notice"><%= notice %></p>
<h3>Welcome to Sports Marketplace <%= current_user[:name] %>  </h3>

app/views/templates/new.html.erb
<h1>New Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @template.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @template.desc %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>